// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgKo8T4Hdtp9tMrf8LKWFTE9MrFcKM-kU',
    appId: '1:727758175293:web:8a4bbb96768cb8ddd43e54',
    messagingSenderId: '727758175293',
    projectId: 'workout-6f396',
    authDomain: 'workout-6f396.firebaseapp.com',
    storageBucket: 'workout-6f396.appspot.com',
    measurementId: 'G-KCP9S14QJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8sLyKo96fH_r58ELK2IyJElujOn8PvN0',
    appId: '1:727758175293:android:18ca33bf03eca0dcd43e54',
    messagingSenderId: '727758175293',
    projectId: 'workout-6f396',
    storageBucket: 'workout-6f396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQsR2NeM_R35lFZTuFT6DcTFkn_n2coc',
    appId: '1:727758175293:ios:36dd7908fbf22339d43e54',
    messagingSenderId: '727758175293',
    projectId: 'workout-6f396',
    storageBucket: 'workout-6f396.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQsR2NeM_R35lFZTuFT6DcTFkn_n2coc',
    appId: '1:727758175293:ios:36dd7908fbf22339d43e54',
    messagingSenderId: '727758175293',
    projectId: 'workout-6f396',
    storageBucket: 'workout-6f396.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgKo8T4Hdtp9tMrf8LKWFTE9MrFcKM-kU',
    appId: '1:727758175293:web:55fd21c1b0adab7ad43e54',
    messagingSenderId: '727758175293',
    projectId: 'workout-6f396',
    authDomain: 'workout-6f396.firebaseapp.com',
    storageBucket: 'workout-6f396.appspot.com',
    measurementId: 'G-WFF4QHEJTG',
  );
}
